### ISSUE TITLE
[BUG] Bad HTML rendering

### ISSUE THREAD

**Issue by Luis-Licea** [TheAbhijeet/djangocentral-bugs-and-features#1]
**Describe the bug**
The following page shows the following text, and I believe this is because the HTML was not rendered directly. https://djangocentral.com/how-to-install-django/ 
[box type="info" align="" class="" width=""]Using Python 3.x+ is highly advised because Django 2.0+ is strictly for Python 3[/box]

**To Reproduce**
1. Go to [How To Install Django](https://djangocentral.com/how-to-install-django/)
2. Scroll down to Installing Django
3. See error

**Expected behavior**
The text "Using Python 3.x+ is highly advised because Django 2.0+ is strictly for Python 3" should display correctly.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox

**Comment by TheAbhijeet** [comment]
Thanks, @Luis-Licea for bringing this to my attention, it's been fixed now.
